DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_AUTH CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE PDS CASCADE CONSTRAINTS;
DROP TABLE PDS_FILE CASCADE CONSTRAINTS;
DROP TABLE ACCESS_LOG CASCADE CONSTRAINTS;
DROP TABLE PERFORMANCE_LOG CASCADE CONSTRAINTS;


-- 회원 테이블
CREATE TABLE MEMBER (
    USER_NO NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    USER_ID VARCHAR2(50) NOT NULL UNIQUE,
    USER_PW VARCHAR2(200) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    JOB VARCHAR2(3) NOT NULL,
    REG_DATE  DATE DEFAULT SYSDATE,
    UPD_DATE  DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MEMBER PRIMARY KEY(USER_NO)
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PW IS '회원암호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.JOB IS '회원직업';
COMMENT ON COLUMN MEMBER.REG_DATE IS '회원가입날짜';
COMMENT ON COLUMN MEMBER.UPD_DATE IS '회원정보수정날짜';

-- 권한 테이블
CREATE TABLE MEMBER_AUTH (
    USER_AUTH_NO NUMBER CONSTRAINT PK_MEMAUTH PRIMARY KEY,
    USER_NO NUMBER,
    AUTH VARCHAR2(50),
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USERNO FOREIGN KEY(USER_NO) 
        REFERENCES MEMBER ON DELETE CASCADE
);

COMMENT ON COLUMN MEMBER_AUTH.USER_AUTH_NO IS '권한등록번호';
COMMENT ON COLUMN MEMBER_AUTH.USER_NO IS '권한부여회원번호';
COMMENT ON COLUMN MEMBER_AUTH.USER_AUTH IS '권한';
COMMENT ON COLUMN MEMBER_AUTH.REG_DATE IS '권한등록날짜';
COMMENT ON COLUMN MEMBER_AUTH.UPD_DATE IS '권한수정날짜';

-- 게시판 테이블
CREATE TABLE BOARD (
    BOARD_NO NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    CONTENT LONG,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_BWRITER FOREIGN KEY (WRITER) 
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.WRITER IS '게시글작성자아이디';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.REG_DATE IS '게시글등록날짜';
COMMENT ON COLUMN BOARD.UPD_DATE IS '게시글수정날짜';

CREATE SEQUENCE SEQ_BOARDNO;

-- 공지사항 테이블
CREATE TABLE NOTICE (
    NOTICE_NO NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT LONG,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_NOTICENO;

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지글번호';
COMMENT ON COLUMN NOTICE.TITLE IS '공지글제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '공지글내용';
COMMENT ON COLUMN NOTICE.REG_DATE IS '공지글등록날짜';
COMMENT ON COLUMN NOTICE.UPD_DATE IS '공지글수정날짜';

-- 자료실 테이블
CREATE TABLE PDS (
    ITEM_ID NUMBER,
    ITEM_NAME VARCHAR2(255),
    VIEW_CNT NUMBER(10),
    DESCRIPTION VARCHAR2(255),
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_REFROOM PRIMARY KEY(ITEM_ID)
);

CREATE SEQUENCE SEQ_PDS;

COMMENT ON COLUMN PDS.ITEM_ID IS '자료번호';
COMMENT ON COLUMN PDS.ITEM_NAME IS '자료이름';
COMMENT ON COLUMN PDS.VIEW_CNT IS '자료조회수';
COMMENT ON COLUMN PDS.DESCRIPTION IS '자료설명';
COMMENT ON COLUMN PDS.REG_DATE IS '자료등록날짜';
COMMENT ON COLUMN PDS.UPD_DATE IS '자료수정날짜';

-- 자료실 파일첨부 테이블
CREATE TABLE PDS_FILE (
    REF_FILE_ID NUMBER CONSTRAINT PK_RRFILE PRIMARY KEY,
    ITEM_ID NUMBER,
    FULL_NAME VARCHAR2(200),
    DOWN_CNT NUMBER,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REFITEMID FOREIGN KEY(ITEM_ID) 
    REFERENCES REFROOM ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PDS_FILEID;

COMMENT ON COLUMN PDS_FILE.REF_FILE_ID IS '첨부파일번호';
COMMENT ON COLUMN PDS_FILE.ITEM_ID IS '자료번호';
COMMENT ON COLUMN PDS_FILE.FULL_NAME IS '첨부파일명';
COMMENT ON COLUMN PDS_FILE.DOWN_CNT IS '파일다운횟수';
COMMENT ON COLUMN PDS_FILE.REG_DATE IS '첨부파일업로드날짜';
COMMENT ON COLUMN PDS_FILE.UPD_DATE IS '첨부파일변경날짜';

-- 접근 로그 테이블
CREATE TABLE ACCESS_LOG (
    LOG_NO NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    REQUEST_URL VARCHAR2(200),
    CLASS_NAME VARCHAR2(100) NOT NULL,
    CLASS_SIMPLE_NAME VARCHAR2(50) NOT NULL,
    METHOD_NAME VARCHAR2(100) NOT NULL,
    REMOTE_ADDR VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_ACCESSLOG PRIMARY KEY(LOG_NO)
);

COMMENT ON COLUMN ACCESS_LOG.LOG_NO IS '로그등록번호';
COMMENT ON COLUMN ACCESS_LOG.REQUEST_URL IS '요청URL';
COMMENT ON COLUMN ACCESS_LOG.CLASS_NAME IS '실행클래스이름';
COMMENT ON COLUMN ACCESS_LOG.CLASS_SIMPLE_NAME IS '간단클래스명';
COMMENT ON COLUMN ACCESS_LOG.METHOD_NAME IS '실행메소드명';
COMMENT ON COLUMN ACCESS_LOG.REMOTE_ADDR IS '클라이언트 IP주소';
COMMENT ON COLUMN ACCESS_LOG.REG_DATE IS '로그등록날짜';
COMMENT ON COLUMN ACCESS_LOG.UPD_DATE IS '로그변경날짜';

-- 서비스 성능 로그 테이블
CREATE TABLE PERFORMANCE_LOG (
    LOG_NO NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    SIGNATURE_NAME VARCHAR2(50) NOT NULL,
    SIGNATURE_TYPE_NAME VARCHAR2(100) NOT NULL,
    DURATION_TIME NUMBER,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PERLOGNO PRIMARY KEY(LOG_NO)
);

COMMENT ON COLUMN PERFORMANCE_LOG.LOG_NO IS '로그번호';
COMMENT ON COLUMN PERFORMANCE_LOG.SIGNATURE_NAME IS '서비스명';
COMMENT ON COLUMN PERFORMANCE_LOG.SIGNATURE_TYPE_NAME IS '서비스타입';
COMMENT ON COLUMN PERFORMANCE_LOG.DURATION_TIME IS '서비스소요시간';
COMMENT ON COLUMN PERFORMANCE_LOG.REG_DATE IS '로그등록날짜';
COMMENT ON COLUMN PERFORMANCE_LOG.UPD_DATE IS '로그변경날짜';


COMMIT;
